config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :facilities do
    resources :boilers 
  end

   root 'facilities#index'

end

app/models/boiler.rb
class Boiler < ActiveRecord::Base
  belongs_to :facility
end

app/models/facility.rb
class Facility < ActiveRecord::Base
    has_many :boilers, dependent: :destroy
end

app/models/facility_search.rb
class FacilitySearch
  attr_reader :date_from, :date_to
  
  def initialize(params)
    params ||= {}
    @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.to_s)
  end
  
  def scope
    Facility.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end
  
  private
  
  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boilers_controller.rb
class BoilersController < ApplicationController
  before_action :set_boiler, only: [:show, :edit, :update, :destroy]

  # GET /boilers
  # GET /boilers.json
  def index
    @facility = Facility.find(params[:facility_id])
    @boilers = @facility.boilers.all
    #@boilers = Boiler.all
  end

  # GET /boilers/1
  # GET /boilers/1.json
  def show
  end

  # GET /boilers/new
  def new
    @facility = Facility.find(params[:facility_id])
    @boilers = @facility.boilers.new
    #@boiler = Boiler.new
  end

  # GET /boilers/1/edit
  def edit
  end

  # POST /boilers
  # POST /boilers.json
  def create
    @facility = Facility.find(params[:facility_id])
    @boiler = @facility.boilers.create(boiler_params)

    respond_to do |format|
      if @boiler.save
        format.html { redirect_to facility_path(@facility), notice: 'Boiler was successfully created.' }
        #format.json { render :show, status: :created, location: @boiler }
      else
        format.html { render :new }
        #format.json { render json: @boiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boilers/1
  # PATCH/PUT /boilers/1.json
  def update
    respond_to do |format|
      if @facility.boilers.update(boiler_params)
        format.html { redirect_to facility_path(@facility), notice: 'Boiler was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility.boiler }
      else
        format.html { render :edit }
        format.json { render json: @facility.boiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boilers/1
  # DELETE /boilers/1.json
  def destroy
        @boiler.destroy
    redirect_to facility_path(@facility)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boiler
      @facility = Facility.find(params[:facility_id])
      @boiler = @facility.boilers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boiler_params
      params.require(:boiler).permit(:make, :manfacture, :year, :facility_id)
    end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  # GET /facilities
  # GET /facilities.json
  def index
     @facilities = Facility.all
    unless 
      @search = FacilitySearch.new(params[:search])
      @facilities = @search.scope
    end
    
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:name, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boilers_helper.rb
module BoilersHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/boilers/_error.html.erb
<% if @facility.boilers.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility.boilers.errors.count, "error") %> prohibited this boiler from being saved:</h2>

      <ul>
      <% @facility.boilers.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/boilers/_form.html.erb
<%= form_for([@facility, @facility.boilers.build]) do |f| %>
  
<table class="table">
  <tr>
    <td>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  </td>
    <td>
  <div class="field">
    <%= f.label :manfacture %><br>
    <%= f.text_field :manfacture %>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.datetime_select :year %>
  </div>
  </td>
  
  </br>
  <tr>
    <td>
  <div class="actions">
    <%= f.submit  %>
  </div>
  </td>
  </tr>
  </tr>
  
<% end %>
</table>
  

app/views/boilers/edit.html.erb
<h1>Editing Boiler</h1>

<%= render 'form' %>

<%= link_to 'Show', facility_boiler_path(@facility, @boiler) %> |
<%= link_to 'Back', facility_boilers_path(@facility) %>

app/views/boilers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boilers</h1>
<div class="media">
  <div class="media-body">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Make</th>
      <th>manfacture</th>
      <th>Year</th>
      <th>Facility</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boilers.each do |boiler| %>
      <tr>
        <td><%= boiler.make %></td>
        <td><%= boiler.manfacture %></td>
        <td><%= boiler.year.strftime("%m/%d/%Y") %></td>
        <td><%= boiler.facility.name %></td>
        <td><%= link_to 'Show', facility_boiler_path(@facility, boiler), class: "btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_facility_boiler_path(@facility, boiler), class: "btn btn-success btn-sm" %></td>
        <td><%= link_to 'Delete', [boiler.facility, boiler],
               method: :delete,
               data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<br>

<%= link_to 'New Boiler', new_facility_boiler_path(@facility), class: "btn btn-primary btn-sm" %> </br>

app/views/boilers/new.html.erb
<h1>New Boiler</h1>

<%= render 'form' %>

<%= link_to 'Back', facility_boilers_path(@facility) %>

app/views/boilers/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
  <thead>
    <tr>
      <th>Make</th>
      <th>manfacture</th>
      <th>Year</th>
      <th>Facility</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
<p>
  <%= @boiler.make %>
</p>
</td>
<td>
<p>
  <%= @boiler.manfacture %>
</p>
</td>
<td>
<p>
  <%= @boiler.year.strftime("%m/%d/%Y") %>
</p>
</td>
<td>
<p>
  <%= @boiler.facility.name %>
</p>
</td>
</tr>
</tbody>
</table>

<%= link_to 'Edit', edit_facility_boiler_path(@facility, @boiler) %> |
<%= link_to 'Back', facility_boilers_path(@facility) %>

app/views/facilities/_form.html.erb
<%= form_for(@facility) do |f| %>
  <% if @facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% @facility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facilities/edit.html.erb
<h1>Editing Facility</h1>

<%= render 'form' %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<h1>Listing Facilities</h1>
  <div class="pull-right range-query">
    <%= form_tag facilities_path, method: :get do %>
    <%= text_field_tag 'search[date_form]', @search.date_from %>
    <%= text_field_tag 'search[date_form]', @search.date_to %>
    <%= submit_tag 'search', class: 'btn search-button' %>
    <% end %>
  </div>
</div>
  
<div class="media">
  <div class="media-body">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facilities.each do |facility| %>
      <tr>
        <td><%= facility.name %></td>
        <td><%= facility.date.strftime("%m/%d/%Y") %></td>
        <td><%= link_to 'Show', facility, class: "btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_facility_path(facility), class: "btn btn-success btn-sm" %></td>
        <td><%= link_to 'Destroy', facility, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>

<%= link_to 'New Facility', new_facility_path, class: "btn btn-primary btn-sm" %>

app/views/facilities/new.html.erb
<h1>New Facility</h1>

<%= render 'form' %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <th>
  <tr>
    <td>
    <strong>Name:</strong>
    </td>
  </tr>
  </th>
  <tr>
    <td>
    <%= @facility.name %>
    </td>
  </tr>
  <th>
  <tr>
    <td>
    <strong>Date:</strong>
    </td>
  </tr>
  </th>
  <tr>
    <td>
    <%= @facility.date.strftime("%m/%d/%Y") %>
    </td>
  </tr>
  </tr>
</table>
<%= link_to 'Facility Boilers', facility_boilers_path(@facility), class: "btn btn-primary" %>

<p><strong> Facility's Boilers</strong></p>
<table class="table">
  <thead>
    <tr>
      <th>Make</th>
      <th>Type</th>
      <th>Year</th>
      <th>Facility</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facility.boilers.each do |boiler| %>
      <tr>
        <td><%= boiler.make %></td>
        <td><%= boiler.manfacture %></td>
        <td><%= boiler.year %></td>
        <td><%= boiler.facility.name %></td>
        <td><%= link_to 'Show', [boiler.facility, boiler], class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', [boiler.facility, boiler], class: "btn btn-success" %></td>
        <td><%= link_to 'Delete', [boiler.facility, boiler],
               method: :delete,
               data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Add a Boiler</h2>
<%= render 'boilers/form' %></br>
<%= link_to 'Edit', edit_facility_path(@facility) %> |
  
<%= link_to 'Back', facilities_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Boilerinspect" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Boilerinspect", root_path, class: "navbar-brand" %></li>
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

<hr>
      <footer>
        <p>&copy; Company <%= Time.now.year %></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>